A decision tree is one of the most powerful algorithms of supervised learning algorithms used for solving regression and classification problem


A decision tree’s topmost node is called a root node. This node partitions the tree recursively based on attribute values, 
which is known as recursive partitioning. The resulting flow chart-like structure is an excellent tool for decision-making
because it mimics human-level thinking. Decision trees are a method of solving specific problems
through the use of nested if-else statements. These trees are visualized through nodes, which represent different decision point



How the features are selected?
Information gain is a measure used to determine which feature should be used to split the data at each internal node of the decision tree



