[[decision tree]]

content = """

https://medium.com/towardsdev/machine-learning-algorithms-8-decision-tree-algorithm-533b6926ddbb


"""

[[timeseries]]

content ="""
https://www.kaggle.com/code/sercanyesiloz/electricity-production-forecasting-arima
https://www.kaggle.com/code/nageshsingh/predict-electricity-consumption/noteb
"""
