[simple_ml_classification]
  description = "Builds a basic classification model using scikit-learn with the Iris dataset. Utilizes K-Nearest Neighbors (KNN) algorithm. Loads Iris dataset, splits it into training and testing sets, creates and trains a KNN model, makes predictions, and evaluates accuracy."
  code_snippet = '''
    from sklearn.datasets import load_iris
    from sklearn.model_selection import train_test_split
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.metrics import accuracy_score

    iris = load_iris()
    X = iris.data
    y = iris.target

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    model = KNeighborsClassifier(n_neighbors=3)
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    print(f"Accuracy: {accuracy}")
  '''
