[machine_learning_example]
  description = "Example of machine learning using scikit-learn. Utilizes Linear Regression for predictions. Loads dataset, splits it into training and testing sets, creates and trains a Linear Regression model, and makes predictions."
  code_snippet = '''
    from sklearn.model_selection import train_test_split
    from sklearn.linear_model import LinearRegression

    # Load dataset and split into features and target
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

    # Create and train a linear regression model
    model = LinearRegression()
    model.fit(X_train, y_train)

    # Make predictions
    predictions = model.predict(X_test)
  '''
